### ISSUE TITLE
Productive Installation

### ISSUE THREAD

**Issue by c-sakel** [chaskiq/chaskiq#165]
Hello,
how do I install the software for production use on Docker or Ubuntu?
Thanks

**Comment by svoop** [comment]
All current [install instructions](https://dev.chaskiq.io/en/collections/getting-started) are "for development", any chance to add a "Docker for production" section?

Meanwhile, do you have a plan as which is going to be your recommended way to install Chaskiq with Docker for production?

* Similar to development by use of `docker-compose`
* With a ready-made image on Docker Hub

I'm a Rails dev, but quite new to Docker. Pulling the image currently on Docker Hub doesn't do much when pulled and started on my local Docker... most likely due to ignorance from my part. :wink:

**Comment by michelson** [comment]
Hi @svoop , unfortunately there is no documentation about the docker for production. but the production image should work as is, it has everything built, gems and node modules precompiled and ready to use. 
we have our production instance working with that image with K8s though

I will keep this open until we document this procedure properly.

**Comment by svoop** [comment]
@michelson Thanks for your reply, the real problem here is my as of yet a little spotty Docker experience. Running it locally on my Mac, I don't see how to discover e.g. which ports to use in order to access the dockerized webserver. However, maybe I should take the `docker-compose` path in the first place because I'd like Chaskiq to use PostgreSQL and Redis on the host and not run their own inside the Docker container. Do I understand  "ready to use" correctly as "PostgreSQL and Redis are part of the production image"?

**Comment by michelson** [comment]
for local development there is indeed the the docker-development which will call the Dockerfile.development. For production there is the chaskiq image, it's already used in production so it's working ok. I guess you must pass the proper env vars.

main ones are:
```
export HOST=https://xx.io
export ASSET_HOST=https://xx.io
export WS=wss://xx.io/cable
export CABLE_URL=wss://xx.io/cable
export DATABASE_URL=postgresql://user:pass@host
export REDIS_URL=rediss://user:pass@host
````

and make to map your HOST to your /etc/host file

**Comment by michelson** [comment]
Hi , I've added some articles on production deployment, one for Caprover and for digital Ocean apps, 
https://dev.chaskiq.io/en/collections/production-configuration

**Comment by eelco2k** [comment]
Here is a small docker-compose.yml with .env file and docker-entrypoint.sh which can get you started:
you should also create a data folder on the same level as the files below. Also make sure you change the .env file with the correct settings as explained at: [env variables configuration](https://dev.chaskiq.io/production-configuration/enviroment-variables-configuration)

docker-compose.yaml
```
version: "3"
networks:
  chaskiq:

services:
  chaskiq-frontend:
    container_name: chaskiq-frontend
    image: chaskiq/chaskiq:latest
    depends_on:
      - chaskiq-postgres
      - chaskiq-redis
    networks:
      - chaskiq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
    env_file:
      - .env
    ports:
      - "3000:3000"

  chaskiq-sidekiq:
    image: chaskiq/chaskiq:latest
    container_name: chaskiq-sidekiq
    depends_on:
      - chaskiq-frontend
      - chaskiq-postgres
      - chaskiq-redis
    networks:
      - chaskiq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - .env

  chaskiq-postgres:
    image: postgres:14-alpine
    container_name: chaskiq-postgres
    restart: always
    networks:
      - chaskiq
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${DB_PORT}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -p ${DB_PORT} -h ${DB_HOST}
      interval: 2s

  chaskiq-redis:
    image: redis:5-alpine
    container_name: chaskiq-redis
    restart: always
    networks:
      - chaskiq
    volumes:
      - ./data/redis:/data
    env_file:
      - .env
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
```

.env
```
HOST = http://0.0.0.0:3000
WS = ws://0.0.0.0:3000/cable
ADMIN_EMAIL =
ADMIN_PASSWORD =

POSTGRES_USER = postgres
POSTGRES_PASSWORD = password
DB_HOST = chaskiq-postgres
DB_PORT = 5432

DATABASE_URL = postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$DB_HOST:$DB_PORT
#DISABLE_DATABASE_ENVIRONMENT_CHECK = 1

REDIS_URL = redis://chaskiq-redis:6379/
APP_ENV = production
RAILS_ENV = production
RACK_ENV = production
RAILS_SERVE_STATIC_FILES = true
SECRET_KEY_BASE =
RAILS_LOG_TO_STDOUT = false

LOCAL_STORAGE_PATH = ./data/storage
ACTIVE_STORAGE_SERVICE = local

AWS_ACCESS_KEY_ID =
AWS_SECRET_ACCESS_KEY =
AWS_S3_BUCKET =
AWS_S3_REGION =
SES_ADDRESS =
SES_USER_NAME =
SES_PASSWORD =
SNS_CONFIGURATION_SET =
DEFAULT_SENDER_EMAIL =
DEFAULT_OUTGOING_EMAIL_DOMAIN =
BUGSNAG_API_KEY =
SMTP_DELIVERY_METHOD =
SMTP_ADDRESS =
SMTP_USERNAME =
SMTP_PASSWORD =
ENABLED_AUDITS = true
CHASKIQ_APPSTORE_TOKEN=

POSTGRES_INITDB_ARGS = --data-checksums
PSQL_HISTFILE = /root/log/.psql_history

```

docker-entrypoint.sh

```
#!/bin/sh

set -e

# Remove a potentially pre-existing server.pid for Rails.
rm -f /app/tmp/pids/server.pid

# Then exec the container's main process (what's set as CMD in the Dockerfile).
exec "$@"


# Wait until Postgres is ready before running the next step.

while ! pg_isready -q -h $DB_HOST -p $DB_PORT -U $POSTGRES_USER

do

    echo "$(date) - waiting for database to start."
    sleep 2

done


# # If the database exists, migrate. Otherwise setup (create and migrate)

echo "Running database migrations..."

bundle exec rails db:migrate 2>/dev/null || bundle exec rails db:setup db:migrate

echo "Finished running database migrations."

echo "Running packages update..."
bundle exec rails packages:update
echo "Finished packages update."

# Generate Admin account
bundle exec rake admin_generator

bundle exec rails s -b 0.0.0.0 -p 3000


```
