### ISSUE TITLE
Syntax error after installing chaskiq

### ISSUE THREAD

**Issue by TobiasGrether** [chaskiq/chaskiq#953]
**Describe the bug**

**To Reproduce**
1. Install with the docker compose file provided below
2. Visit the login page
3. Try to login once

**Expected behavior**
Login to work just fine

**Screenshots**
Browser errors out with a Syntax Error, the application page remains blank, even from an incognito tab or different browser
```
caught SyntaxError: Invalid or unexpected token
at appplication-e525db036a4462eb4471044959cea9ff090e1961.js:8209:12464
```

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser Brave, Safari
 - Version MacOS 13.4, Brave 1.51.111

**Additional context**
```
---
version: "3"

services:
  server:
    image: chaskiq/chaskiq:latest
    env_file: [".env"]
    restart: always
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - chask

  worker:
    image: chaskiq/chaskiq:latest
    env_file:
    - .env
    container_name: worker
    restart: always
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - postgres
      - redis
    networks:
      - chask

  postgres:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_DATABASE: chask
    volumes:
      - postgres:/bitnami/postgresql
    networks:
      - chask

  redis:
    image: redis:latest
    restart: always
    networks:
      - chask

networks:
  chask:
    name: chask
    driver: bridge

volumes:
  postgres:
    driver: local
 ```
